'use client'

/**
 * CHAT TAB — the centerpiece of the portal.
 *
 * FUTURE INTEGRATION:
 * - Wallet connect uses Xaman (XRPL). The "Connect" button here simulates the
 *   Xaman sign-in / xApp deep-link flow and NFT lookup.
 * - AI replies will be generated by OpenRouter using each Bro's `systemPrompt`
 *   plus chat history persisted in Supabase.
 * - Trade bot buttons will control the XRPL trading bot process.
 */

import { useCallback, useRef, useState } from 'react'
import { Sparkles, Zap } from 'lucide-react'
import type { GrossBro } from '@/lib/gross-bros'
import { NftIdentityCard } from '@/components/chat/nft-identity-card'
import { TradeBotPanel, type BotAction } from '@/components/chat/trade-bot-panel'
import { ChatPanel, type ChatMessage } from '@/components/chat/chat-panel'

let idc = 0
const nextId = () => `m${++idc}`

export function ChatTab({
  connected,
  bro,
  connecting,
  onConnect,
}: {
  connected: boolean
  bro: GrossBro
  connecting: boolean
  onConnect: () => void
}) {
  const [messages, setMessages] = useState<ChatMessage[]>([
    { id: nextId(), role: 'system', text: 'NEURAL LINK ESTABLISHED' },
    {
      id: nextId(),
      role: 'bro',
      text: `${bro.demoReplies[0]}`,
    },
  ])
  const [typing, setTyping] = useState(false)
  const [botOn, setBotOn] = useState(false)
  const [autonomous, setAutonomous] = useState(false)
  const replyIdx = useRef(1)

  const broReply = useCallback(
    (text: string) => {
      setTyping(true)
      window.setTimeout(() => {
        setTyping(false)
        setMessages((prev) => [...prev, { id: nextId(), role: 'bro', text }])
      }, 900)
    },
    [],
  )

  const handleSend = useCallback(
    (text: string) => {
      setMessages((prev) => [...prev, { id: nextId(), role: 'user', text }])
      // DEMO: cycle through canned replies. Replace with OpenRouter call.
      const reply = bro.demoReplies[replyIdx.current % bro.demoReplies.length]
      replyIdx.current += 1
      broReply(reply)
    },
    [bro, broReply],
  )

  const handleBotAction = useCallback(
    (action: BotAction) => {
      const push = (text: string) =>
        setMessages((prev) => [...prev, { id: nextId(), role: 'system', text }])

      switch (action) {
        case 'toggle': {
          const next = !botOn
          setBotOn(next)
          push(next ? 'TRADE BOT ONLINE' : 'TRADE BOT OFFLINE')
          broReply(
            next
              ? 'Bot is hot, holder. I am watching every candle on XRP-7 for you. 🟢'
              : 'Bot powered down. We rest, we regroup, we ride again.',
          )
          break
        }
        case 'deposit':
          push('DEPOSIT REQUESTED')
          broReply('Send the XRP over and I will feed it into the fusion core. Every drop counts.')
          break
        case 'withdraw':
          push('WITHDRAW REQUESTED')
          broReply('Pulling your funds out clean — no slime residue, I promise.')
          break
        case 'status':
          push('STATUS PING')
          broReply(
            `Status: bot is ${botOn ? 'ACTIVE' : 'OFFLINE'}, autonomous ${autonomous ? 'ON' : 'OFF'}. All systems gross and green.`,
          )
          break
        case 'autonomous': {
          const next = !autonomous
          setAutonomous(next)
          push(next ? 'AUTONOMOUS MODE ENGAGED' : 'AUTONOMOUS MODE DISENGAGED')
          broReply(
            next
              ? 'Handing me the wheel? Bold. I will trade like a true XRP-7 rebel.'
              : 'Back to manual. You call the shots, holder.',
          )
          break
        }
      }
    },
    [botOn, autonomous, broReply],
  )

  if (!connected) {
    return <ConnectGate bro={bro} connecting={connecting} onConnect={onConnect} />
  }

  return (
    <div className="mx-auto grid max-w-6xl gap-4 lg:grid-cols-[minmax(0,340px)_1fr]">
      {/* Left: identity + bot controls */}
      <div className="space-y-4">
        <NftIdentityCard bro={bro} />
        <TradeBotPanel botOn={botOn} autonomous={autonomous} onAction={handleBotAction} />
      </div>

      {/* Right: chat */}
      <div className="h-[560px] min-h-[520px] lg:h-[720px]">
        <ChatPanel bro={bro} messages={messages} typing={typing} onSend={handleSend} />
      </div>
    </div>
  )
}

function ConnectGate({
  bro,
  connecting,
  onConnect,
}: {
  bro: GrossBro
  connecting: boolean
  onConnect: () => void
}) {
  return (
    <div className="mx-auto flex max-w-md flex-col items-center px-2 py-10 text-center">
      <div className="relative mb-6 grid size-24 place-items-center rounded-3xl border border-primary/30 bg-primary/5 neon-border float-slow">
        <div className="size-10 rounded-full bg-primary neon-ring" />
      </div>
      <p className="mb-2 font-mono text-[11px] uppercase tracking-[0.3em] text-primary">
        XRP-7 · REBELLION NET
      </p>
      <h1 className="mb-3 text-3xl font-bold tracking-tight text-balance">
        Link your <span className="text-primary text-glow">Gross Bro</span>
      </h1>
      <p className="mb-8 text-sm leading-relaxed text-muted-foreground text-pretty">
        Connect your XRPL wallet with Xaman to summon your Gross Bro NFT. Each Bro
        has its own personality, backstory, and trade bot — ready to fight the
        Ledger Wars beside you.
      </p>

      <button
        type="button"
        onClick={onConnect}
        disabled={connecting}
        className="flex w-full items-center justify-center gap-2 rounded-xl bg-primary px-5 py-3.5 text-sm font-semibold text-primary-foreground transition-all hover:opacity-90 disabled:opacity-70 neon-ring"
      >
        {connecting ? (
          <>
            <span className="typing-dot size-1.5 rounded-full bg-primary-foreground" />
            Summoning {bro.name}...
          </>
        ) : (
          <>
            <Sparkles className="size-4" />
            Connect Xaman Wallet
          </>
        )}
      </button>

      <div className="mt-6 flex items-center gap-2 text-xs text-muted-foreground">
        <Zap className="size-3.5 text-primary" />
        Powered by XRPL · Xaman · OpenRouter
      </div>
    </div>
  )
}
