import { NextResponse } from 'next/server';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

const XRPL = 'https://api.xrpl.to/v1';
const OTD = 'https://api.onthedex.live/public/v1';
const OR = 'https://openrouter.ai/api/v1/chat/completions';
const MODEL = process.env.OPENROUTER_MODEL || 'openai/gpt-4o-mini';

type Msg = { role?: string; text?: string; content?: string };
type Token = { _id?: string; md5?: string; currency?: string; issuer?: string; name?: string; token?: string; usd?: number | string; price?: number | string; exch?: number | string; priceUsd?: number | string; pro24h?: number | string; priceChange24h?: number | string; price_mid_usd?: number | string; volume_usd?: number };

async function getJson<T>(url: string, init: RequestInit = {}): Promise<T> {
  const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), 10000);
  try { const response = await fetch(url, { ...init, signal: controller.signal, cache: 'no-store', headers: { Accept: 'application/json', 'User-Agent': 'Gross-Bros-Fusion/1.0 (server-side market data)', Referer: 'https://xrpl.to/', ...(init.headers || {}) } }); if (!response.ok) throw new Error(`HTTP ${response.status}`); const value = await response.json() as T; if ((value as any)?.error) throw new Error((value as any).message || (value as any).error); return value; } finally { clearTimeout(timer); }
}
function number(...values: unknown[]): number | undefined { for (const value of values) { const n = Number(value); if (Number.isFinite(n) && n > 0) return n; } return undefined; }
async function xrpPrice() { const data = await getJson<any>('https://api.coingecko.com/api/v3/simple/price?ids=ripple&vs_currencies=usd&include_24hr_change=true'); const p = number(data?.ripple?.usd); if (!p) throw new Error('XRP price unavailable'); return { symbol: 'XRP', name: 'XRP', priceUsd: p, change24h: data.ripple.usd_24h_change, source: 'CoinGecko', updatedAt: new Date().toISOString() }; }
async function resolveXrpl(query: string) { const response = await getJson<{ tokens?: Token[] }>(`${XRPL}/search`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ search: query, limit: 20 }) }); const q = query.toLowerCase(); return (response.tokens || []).sort((a, b) => ((String(b.currency || '').toLowerCase() === q ? 100 : 0) + (String(b.name || '').toLowerCase() === q ? 80 : 0) + Number(b.volume_usd || 0) / 1e9) - ((String(a.currency || '').toLowerCase() === q ? 100 : 0) + (String(a.name || '').toLowerCase() === q ? 80 : 0) + Number(a.volume_usd || 0) / 1e9))[0]; }
async function xrplPrice(query: string) { const issuer = query.match(/r[1-9A-HJ-NP-Za-km-z]{24,34}/)?.[0]; const symbol = query.replace(issuer || '', '').replace(/[.\s]/g, '') || query; const token = issuer ? { issuer, currency: symbol } : await resolveXrpl(query); if (!token?.issuer || !token?.currency) throw new Error('XRPL token not found'); const p = number(token.usd, token.priceUsd, token.price_mid_usd, token.price, token.exch); if (!p) throw new Error('XRPL token has no live USD price'); return { symbol: token.token || token.currency, name: token.name || token.currency, priceUsd: p, change24h: number(token.pro24h, token.priceChange24h), source: 'XRPL.to', identifier: `${token.issuer}.${token.currency}`, updatedAt: new Date().toISOString() }; }
async function onTheDexPrice(query: string) { const search = await getJson<any>(`${OTD}/daily/tokens?by=volume&min_trades=1&page=1&per_page=100`); const q = query.toLowerCase(); const token = (search.tokens || []).filter((t: any) => String(t.currency || '').toLowerCase() === q || String(t.token_name || '').toLowerCase() === q || String(t.issuer || '').toLowerCase() === q).sort((a: any, b: any) => Number(b.volume_usd || 0) - Number(a.volume_usd || 0))[0]; if (!token) throw new Error('OnTheDEX token not found'); const data = await getJson<any>(`${OTD}/aggregator?token=${encodeURIComponent(`${token.currency}.${token.issuer}`)}`); const row = data.tokens?.[0] || token; const p = number(row.price_mid_usd, token.price_mid_usd); if (!p) throw new Error('OnTheDEX price unavailable'); return { symbol: token.currency, name: row.name || token.token_name || token.currency, priceUsd: p, source: 'OnTheDEX XRPL Ledger API', identifier: `${token.currency}.${token.issuer}`, updatedAt: new Date().toISOString() }; }
function asset(text: string) { if (!/(price|quote|worth|value|cost|trading|trade|market|how much)/i.test(text)) return null; if (/\bxrp\b/i.test(text)) return 'XRP'; const address = text.match(/r[1-9A-HJ-NP-Za-km-z]{24,34}/)?.[0]; const symbol = text.match(/\b[A-Za-z][A-Za-z0-9_-]{1,15}\b/g)?.filter(x => !/price|what|current|worth|much|the|is|of|for|how|token|coin|trading/i.test(x))[0]; return address ? `${symbol || ''}.${address}` : symbol?.toUpperCase() || null; }
function history(body: any, latest: string) { const list = Array.isArray(body?.messages) ? body.messages : []; const result = list.map((m: Msg) => { const content = String(m.content ?? m.text ?? '').trim(); if (!content) return null; return { role: m.role === 'assistant' || m.role === 'bro' ? 'assistant' as const : 'user' as const, content }; }).filter(Boolean).slice(-12) as Array<{ role: 'user' | 'assistant'; content: string }>; if (result.at(-1)?.content !== latest) result.push({ role: 'user', content: latest }); return result; }
async function llm(messages: Array<{ role: 'user' | 'assistant'; content: string }>, prompt?: string) { if (!process.env.OPENROUTER_API_KEY) throw new Error('OPENROUTER_API_KEY is not configured'); const data = await getJson<any>(OR, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${process.env.OPENROUTER_API_KEY}`, 'HTTP-Referer': process.env.OPENROUTER_SITE_URL || 'https://grossbros.vercel.app', 'X-Title': 'Gross Bros Fusion' }, body: JSON.stringify({ model: MODEL, temperature: 0.7, max_tokens: 500, messages: [{ role: 'system', content: prompt || 'You are a witty, helpful XRPL assistant. Never invent live prices or claim to execute trades.' }, ...messages] }) }); const text = data.choices?.[0]?.message?.content?.trim(); if (!text) throw new Error('Empty LLM response'); return text; }
export async function POST(request: Request) { try { const body = await request.json().catch(() => null); const latest = typeof body?.message === 'string' ? body.message.trim() : String(body?.messages?.at?.(-1)?.content ?? body?.messages?.at?.(-1)?.text ?? '').trim(); if (!latest) return NextResponse.json({ ok: false, error: 'A non-empty message is required.' }, { status: 400 }); const requested = asset(latest); if (requested) { try { const price = requested === 'XRP' ? await xrpPrice() : await xrplPrice(requested); return NextResponse.json({ ok: true, bot: false, reply: `${price.symbol} is $${price.priceUsd.toLocaleString(undefined, { maximumFractionDigits: 8 })} USD. Source: ${price.source}.`, price }); } catch (firstError) { console.error('XRPL.to lookup failed:', firstError); try { const price = await onTheDexPrice(requested); return NextResponse.json({ ok: true, bot: false, reply: `${price.symbol} is $${price.priceUsd.toLocaleString(undefined, { maximumFractionDigits: 8 })} USD. Source: ${price.source}.`, price }); } catch (fallbackError) { console.error('OnTheDEX lookup failed:', fallbackError); return NextResponse.json({ ok: true, bot: false, reply: `I could not find a reliable live market for ${requested} right now.` }); } } } const reply = await llm(history(body, latest), body?.systemPrompt); return NextResponse.json({ ok: true, bot: false, reply, text: reply }); } catch (error) { console.error('chat route error:', error); return NextResponse.json({ ok: false, error: error instanceof Error ? error.message : 'Chat service unavailable' }, { status: 502 }); } }
